leftnav:
- identifier: f246a8d7-b709-67bc-3706-5ad637753476
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 95c91868-06b7-958f-3104-a7376b1197a8
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 9a99fde8-9532-6a70-3eca-004b8c62be47
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 4fe1c063-6927-017a-6ce4-813d9764954f
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 12a3271f-7240-23ef-3864-5a1489d47d44
  name: Projects
  pageRef: /pages/projects
  weight: 50
